// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_gbmj.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msg_gbmj.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pt {
namespace zj {
class obj_userDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<obj_user> {
} _obj_user_default_instance_;
class obj_testDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<obj_test> {
} _obj_test_default_instance_;
class xxDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<xx> {
} _xx_default_instance_;

namespace protobuf_msg_5fgbmj_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(obj_user, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(obj_user, s_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(obj_user, arr_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(obj_test, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(obj_test, val_string_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(xx, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(xx, v_1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(xx, v2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(xx, v_x_3_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(xx, test_1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(xx, user_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(xx, str_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(xx, ret_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(xx, username_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(xx, isbool_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(obj_user)},
  { 7, -1, sizeof(obj_test)},
  { 13, -1, sizeof(xx)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_obj_user_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_obj_test_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_xx_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "msg_gbmj.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

}  // namespace

void TableStruct::Shutdown() {
  _obj_user_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _obj_test_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _xx_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _obj_user_default_instance_.DefaultConstruct();
  _obj_test_default_instance_.DefaultConstruct();
  _xx_default_instance_.DefaultConstruct();
  _xx_default_instance_.get_mutable()->test_1_ = const_cast< ::pt::zj::obj_test*>(
      ::pt::zj::obj_test::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\016msg_gbmj.proto\022\005pt.zj\"s\n\010obj_user\022 \n\001s"
      "\030\001 \001(\0162\025.pt.zj.obj_user.STATE\022\013\n\003arr\030\002 \003"
      "(\005\"8\n\005STATE\022\r\n\tS_SUCCESS\020\000\022\017\n\013S_SUCCESS_"
      "1\020\001\022\017\n\013S_SUCCESS_2\020\002\"\036\n\010obj_test\022\022\n\nval_"
      "string\030\001 \001(\t\"\264\001\n\002xx\022\013\n\003v_1\030\001 \001(\005\022\n\n\002v2\030\002"
      " \001(\003\022\r\n\005v_x_3\030\003 \001(\r\022\037\n\006test_1\030\005 \001(\0132\017.pt"
      ".zj.obj_test\022\035\n\004user\030\007 \003(\0132\017.pt.zj.obj_u"
      "ser\022\013\n\003str\030\010 \001(\t\022\027\n\003ret\030\t \001(\0162\n.pt.zj.RE"
      "T\022\020\n\010userName\030\n \001(\t\022\016\n\006isBool\030\013 \001(\010*%\n\003R"
      "ET\022\017\n\013RET_SUCCESS\020\000\022\r\n\tRET_ERROR\020\001b\006prot"
      "o3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 402);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg_gbmj.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_msg_5fgbmj_2eproto

const ::google::protobuf::EnumDescriptor* obj_user_STATE_descriptor() {
  protobuf_msg_5fgbmj_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_msg_5fgbmj_2eproto::file_level_enum_descriptors[0];
}
bool obj_user_STATE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const obj_user_STATE obj_user::S_SUCCESS;
const obj_user_STATE obj_user::S_SUCCESS_1;
const obj_user_STATE obj_user::S_SUCCESS_2;
const obj_user_STATE obj_user::STATE_MIN;
const obj_user_STATE obj_user::STATE_MAX;
const int obj_user::STATE_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* RET_descriptor() {
  protobuf_msg_5fgbmj_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_msg_5fgbmj_2eproto::file_level_enum_descriptors[1];
}
bool RET_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int obj_user::kSFieldNumber;
const int obj_user::kArrFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

obj_user::obj_user()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_msg_5fgbmj_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pt.zj.obj_user)
}
obj_user::obj_user(const obj_user& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      arr_(from.arr_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  s_ = from.s_;
  // @@protoc_insertion_point(copy_constructor:pt.zj.obj_user)
}

void obj_user::SharedCtor() {
  s_ = 0;
  _cached_size_ = 0;
}

obj_user::~obj_user() {
  // @@protoc_insertion_point(destructor:pt.zj.obj_user)
  SharedDtor();
}

void obj_user::SharedDtor() {
}

void obj_user::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* obj_user::descriptor() {
  protobuf_msg_5fgbmj_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_msg_5fgbmj_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const obj_user& obj_user::default_instance() {
  protobuf_msg_5fgbmj_2eproto::InitDefaults();
  return *internal_default_instance();
}

obj_user* obj_user::New(::google::protobuf::Arena* arena) const {
  obj_user* n = new obj_user;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void obj_user::Clear() {
// @@protoc_insertion_point(message_clear_start:pt.zj.obj_user)
  arr_.Clear();
  s_ = 0;
}

bool obj_user::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pt.zj.obj_user)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .pt.zj.obj_user.STATE s = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_s(static_cast< ::pt::zj::obj_user_STATE >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 arr = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_arr())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(16u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 18u, input, this->mutable_arr())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pt.zj.obj_user)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pt.zj.obj_user)
  return false;
#undef DO_
}

void obj_user::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pt.zj.obj_user)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .pt.zj.obj_user.STATE s = 1;
  if (this->s() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->s(), output);
  }

  // repeated int32 arr = 2;
  if (this->arr_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_arr_cached_byte_size_);
  }
  for (int i = 0, n = this->arr_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->arr(i), output);
  }

  // @@protoc_insertion_point(serialize_end:pt.zj.obj_user)
}

::google::protobuf::uint8* obj_user::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pt.zj.obj_user)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .pt.zj.obj_user.STATE s = 1;
  if (this->s() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->s(), target);
  }

  // repeated int32 arr = 2;
  if (this->arr_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _arr_cached_byte_size_, target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->arr_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pt.zj.obj_user)
  return target;
}

size_t obj_user::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pt.zj.obj_user)
  size_t total_size = 0;

  // repeated int32 arr = 2;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->arr_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _arr_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // .pt.zj.obj_user.STATE s = 1;
  if (this->s() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->s());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void obj_user::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pt.zj.obj_user)
  GOOGLE_DCHECK_NE(&from, this);
  const obj_user* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const obj_user>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pt.zj.obj_user)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pt.zj.obj_user)
    MergeFrom(*source);
  }
}

void obj_user::MergeFrom(const obj_user& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pt.zj.obj_user)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  arr_.MergeFrom(from.arr_);
  if (from.s() != 0) {
    set_s(from.s());
  }
}

void obj_user::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pt.zj.obj_user)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void obj_user::CopyFrom(const obj_user& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pt.zj.obj_user)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool obj_user::IsInitialized() const {
  return true;
}

void obj_user::Swap(obj_user* other) {
  if (other == this) return;
  InternalSwap(other);
}
void obj_user::InternalSwap(obj_user* other) {
  arr_.InternalSwap(&other->arr_);
  std::swap(s_, other->s_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata obj_user::GetMetadata() const {
  protobuf_msg_5fgbmj_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_msg_5fgbmj_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// obj_user

// .pt.zj.obj_user.STATE s = 1;
void obj_user::clear_s() {
  s_ = 0;
}
::pt::zj::obj_user_STATE obj_user::s() const {
  // @@protoc_insertion_point(field_get:pt.zj.obj_user.s)
  return static_cast< ::pt::zj::obj_user_STATE >(s_);
}
void obj_user::set_s(::pt::zj::obj_user_STATE value) {
  
  s_ = value;
  // @@protoc_insertion_point(field_set:pt.zj.obj_user.s)
}

// repeated int32 arr = 2;
int obj_user::arr_size() const {
  return arr_.size();
}
void obj_user::clear_arr() {
  arr_.Clear();
}
::google::protobuf::int32 obj_user::arr(int index) const {
  // @@protoc_insertion_point(field_get:pt.zj.obj_user.arr)
  return arr_.Get(index);
}
void obj_user::set_arr(int index, ::google::protobuf::int32 value) {
  arr_.Set(index, value);
  // @@protoc_insertion_point(field_set:pt.zj.obj_user.arr)
}
void obj_user::add_arr(::google::protobuf::int32 value) {
  arr_.Add(value);
  // @@protoc_insertion_point(field_add:pt.zj.obj_user.arr)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
obj_user::arr() const {
  // @@protoc_insertion_point(field_list:pt.zj.obj_user.arr)
  return arr_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
obj_user::mutable_arr() {
  // @@protoc_insertion_point(field_mutable_list:pt.zj.obj_user.arr)
  return &arr_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int obj_test::kValStringFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

obj_test::obj_test()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_msg_5fgbmj_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pt.zj.obj_test)
}
obj_test::obj_test(const obj_test& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  val_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.val_string().size() > 0) {
    val_string_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.val_string_);
  }
  // @@protoc_insertion_point(copy_constructor:pt.zj.obj_test)
}

void obj_test::SharedCtor() {
  val_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

obj_test::~obj_test() {
  // @@protoc_insertion_point(destructor:pt.zj.obj_test)
  SharedDtor();
}

void obj_test::SharedDtor() {
  val_string_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void obj_test::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* obj_test::descriptor() {
  protobuf_msg_5fgbmj_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_msg_5fgbmj_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const obj_test& obj_test::default_instance() {
  protobuf_msg_5fgbmj_2eproto::InitDefaults();
  return *internal_default_instance();
}

obj_test* obj_test::New(::google::protobuf::Arena* arena) const {
  obj_test* n = new obj_test;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void obj_test::Clear() {
// @@protoc_insertion_point(message_clear_start:pt.zj.obj_test)
  val_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool obj_test::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pt.zj.obj_test)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string val_string = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_val_string()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->val_string().data(), this->val_string().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pt.zj.obj_test.val_string"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pt.zj.obj_test)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pt.zj.obj_test)
  return false;
#undef DO_
}

void obj_test::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pt.zj.obj_test)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string val_string = 1;
  if (this->val_string().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->val_string().data(), this->val_string().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pt.zj.obj_test.val_string");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->val_string(), output);
  }

  // @@protoc_insertion_point(serialize_end:pt.zj.obj_test)
}

::google::protobuf::uint8* obj_test::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pt.zj.obj_test)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string val_string = 1;
  if (this->val_string().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->val_string().data(), this->val_string().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pt.zj.obj_test.val_string");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->val_string(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pt.zj.obj_test)
  return target;
}

size_t obj_test::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pt.zj.obj_test)
  size_t total_size = 0;

  // string val_string = 1;
  if (this->val_string().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->val_string());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void obj_test::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pt.zj.obj_test)
  GOOGLE_DCHECK_NE(&from, this);
  const obj_test* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const obj_test>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pt.zj.obj_test)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pt.zj.obj_test)
    MergeFrom(*source);
  }
}

void obj_test::MergeFrom(const obj_test& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pt.zj.obj_test)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.val_string().size() > 0) {

    val_string_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.val_string_);
  }
}

void obj_test::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pt.zj.obj_test)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void obj_test::CopyFrom(const obj_test& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pt.zj.obj_test)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool obj_test::IsInitialized() const {
  return true;
}

void obj_test::Swap(obj_test* other) {
  if (other == this) return;
  InternalSwap(other);
}
void obj_test::InternalSwap(obj_test* other) {
  val_string_.Swap(&other->val_string_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata obj_test::GetMetadata() const {
  protobuf_msg_5fgbmj_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_msg_5fgbmj_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// obj_test

// string val_string = 1;
void obj_test::clear_val_string() {
  val_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& obj_test::val_string() const {
  // @@protoc_insertion_point(field_get:pt.zj.obj_test.val_string)
  return val_string_.GetNoArena();
}
void obj_test::set_val_string(const ::std::string& value) {
  
  val_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pt.zj.obj_test.val_string)
}
#if LANG_CXX11
void obj_test::set_val_string(::std::string&& value) {
  
  val_string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pt.zj.obj_test.val_string)
}
#endif
void obj_test::set_val_string(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  val_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.zj.obj_test.val_string)
}
void obj_test::set_val_string(const char* value, size_t size) {
  
  val_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.zj.obj_test.val_string)
}
::std::string* obj_test::mutable_val_string() {
  
  // @@protoc_insertion_point(field_mutable:pt.zj.obj_test.val_string)
  return val_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* obj_test::release_val_string() {
  // @@protoc_insertion_point(field_release:pt.zj.obj_test.val_string)
  
  return val_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void obj_test::set_allocated_val_string(::std::string* val_string) {
  if (val_string != NULL) {
    
  } else {
    
  }
  val_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val_string);
  // @@protoc_insertion_point(field_set_allocated:pt.zj.obj_test.val_string)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int xx::kV1FieldNumber;
const int xx::kV2FieldNumber;
const int xx::kVX3FieldNumber;
const int xx::kTest1FieldNumber;
const int xx::kUserFieldNumber;
const int xx::kStrFieldNumber;
const int xx::kRetFieldNumber;
const int xx::kUserNameFieldNumber;
const int xx::kIsBoolFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

xx::xx()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_msg_5fgbmj_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pt.zj.xx)
}
xx::xx(const xx& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      user_(from.user_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  str_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.str().size() > 0) {
    str_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.str_);
  }
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.username().size() > 0) {
    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
  if (from.has_test_1()) {
    test_1_ = new ::pt::zj::obj_test(*from.test_1_);
  } else {
    test_1_ = NULL;
  }
  ::memcpy(&v2_, &from.v2_,
    reinterpret_cast<char*>(&isbool_) -
    reinterpret_cast<char*>(&v2_) + sizeof(isbool_));
  // @@protoc_insertion_point(copy_constructor:pt.zj.xx)
}

void xx::SharedCtor() {
  str_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&test_1_, 0, reinterpret_cast<char*>(&isbool_) -
    reinterpret_cast<char*>(&test_1_) + sizeof(isbool_));
  _cached_size_ = 0;
}

xx::~xx() {
  // @@protoc_insertion_point(destructor:pt.zj.xx)
  SharedDtor();
}

void xx::SharedDtor() {
  str_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  username_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) {
    delete test_1_;
  }
}

void xx::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* xx::descriptor() {
  protobuf_msg_5fgbmj_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_msg_5fgbmj_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const xx& xx::default_instance() {
  protobuf_msg_5fgbmj_2eproto::InitDefaults();
  return *internal_default_instance();
}

xx* xx::New(::google::protobuf::Arena* arena) const {
  xx* n = new xx;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void xx::Clear() {
// @@protoc_insertion_point(message_clear_start:pt.zj.xx)
  user_.Clear();
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && test_1_ != NULL) {
    delete test_1_;
  }
  test_1_ = NULL;
  ::memset(&v2_, 0, reinterpret_cast<char*>(&isbool_) -
    reinterpret_cast<char*>(&v2_) + sizeof(isbool_));
}

bool xx::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pt.zj.xx)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 v_1 = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &v_1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 v2 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &v2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 v_x_3 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &v_x_3_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .pt.zj.obj_test test_1 = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_test_1()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .pt.zj.obj_user user = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_user()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string str = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_str()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->str().data(), this->str().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pt.zj.xx.str"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .pt.zj.RET ret = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_ret(static_cast< ::pt::zj::RET >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string userName = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->username().data(), this->username().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pt.zj.xx.userName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool isBool = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(88u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isbool_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pt.zj.xx)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pt.zj.xx)
  return false;
#undef DO_
}

void xx::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pt.zj.xx)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 v_1 = 1;
  if (this->v_1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->v_1(), output);
  }

  // int64 v2 = 2;
  if (this->v2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->v2(), output);
  }

  // uint32 v_x_3 = 3;
  if (this->v_x_3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->v_x_3(), output);
  }

  // .pt.zj.obj_test test_1 = 5;
  if (this->has_test_1()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->test_1_, output);
  }

  // repeated .pt.zj.obj_user user = 7;
  for (unsigned int i = 0, n = this->user_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->user(i), output);
  }

  // string str = 8;
  if (this->str().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->str().data(), this->str().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pt.zj.xx.str");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->str(), output);
  }

  // .pt.zj.RET ret = 9;
  if (this->ret() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      9, this->ret(), output);
  }

  // string userName = 10;
  if (this->username().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pt.zj.xx.userName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->username(), output);
  }

  // bool isBool = 11;
  if (this->isbool() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(11, this->isbool(), output);
  }

  // @@protoc_insertion_point(serialize_end:pt.zj.xx)
}

::google::protobuf::uint8* xx::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pt.zj.xx)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 v_1 = 1;
  if (this->v_1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->v_1(), target);
  }

  // int64 v2 = 2;
  if (this->v2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->v2(), target);
  }

  // uint32 v_x_3 = 3;
  if (this->v_x_3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->v_x_3(), target);
  }

  // .pt.zj.obj_test test_1 = 5;
  if (this->has_test_1()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, *this->test_1_, deterministic, target);
  }

  // repeated .pt.zj.obj_user user = 7;
  for (unsigned int i = 0, n = this->user_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        7, this->user(i), deterministic, target);
  }

  // string str = 8;
  if (this->str().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->str().data(), this->str().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pt.zj.xx.str");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->str(), target);
  }

  // .pt.zj.RET ret = 9;
  if (this->ret() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      9, this->ret(), target);
  }

  // string userName = 10;
  if (this->username().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pt.zj.xx.userName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->username(), target);
  }

  // bool isBool = 11;
  if (this->isbool() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(11, this->isbool(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pt.zj.xx)
  return target;
}

size_t xx::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pt.zj.xx)
  size_t total_size = 0;

  // repeated .pt.zj.obj_user user = 7;
  {
    unsigned int count = this->user_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->user(i));
    }
  }

  // string str = 8;
  if (this->str().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->str());
  }

  // string userName = 10;
  if (this->username().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->username());
  }

  // .pt.zj.obj_test test_1 = 5;
  if (this->has_test_1()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->test_1_);
  }

  // int64 v2 = 2;
  if (this->v2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->v2());
  }

  // int32 v_1 = 1;
  if (this->v_1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->v_1());
  }

  // uint32 v_x_3 = 3;
  if (this->v_x_3() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->v_x_3());
  }

  // .pt.zj.RET ret = 9;
  if (this->ret() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->ret());
  }

  // bool isBool = 11;
  if (this->isbool() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void xx::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pt.zj.xx)
  GOOGLE_DCHECK_NE(&from, this);
  const xx* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const xx>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pt.zj.xx)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pt.zj.xx)
    MergeFrom(*source);
  }
}

void xx::MergeFrom(const xx& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pt.zj.xx)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  user_.MergeFrom(from.user_);
  if (from.str().size() > 0) {

    str_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.str_);
  }
  if (from.username().size() > 0) {

    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
  if (from.has_test_1()) {
    mutable_test_1()->::pt::zj::obj_test::MergeFrom(from.test_1());
  }
  if (from.v2() != 0) {
    set_v2(from.v2());
  }
  if (from.v_1() != 0) {
    set_v_1(from.v_1());
  }
  if (from.v_x_3() != 0) {
    set_v_x_3(from.v_x_3());
  }
  if (from.ret() != 0) {
    set_ret(from.ret());
  }
  if (from.isbool() != 0) {
    set_isbool(from.isbool());
  }
}

void xx::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pt.zj.xx)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void xx::CopyFrom(const xx& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pt.zj.xx)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool xx::IsInitialized() const {
  return true;
}

void xx::Swap(xx* other) {
  if (other == this) return;
  InternalSwap(other);
}
void xx::InternalSwap(xx* other) {
  user_.InternalSwap(&other->user_);
  str_.Swap(&other->str_);
  username_.Swap(&other->username_);
  std::swap(test_1_, other->test_1_);
  std::swap(v2_, other->v2_);
  std::swap(v_1_, other->v_1_);
  std::swap(v_x_3_, other->v_x_3_);
  std::swap(ret_, other->ret_);
  std::swap(isbool_, other->isbool_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata xx::GetMetadata() const {
  protobuf_msg_5fgbmj_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_msg_5fgbmj_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// xx

// int32 v_1 = 1;
void xx::clear_v_1() {
  v_1_ = 0;
}
::google::protobuf::int32 xx::v_1() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.v_1)
  return v_1_;
}
void xx::set_v_1(::google::protobuf::int32 value) {
  
  v_1_ = value;
  // @@protoc_insertion_point(field_set:pt.zj.xx.v_1)
}

// int64 v2 = 2;
void xx::clear_v2() {
  v2_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 xx::v2() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.v2)
  return v2_;
}
void xx::set_v2(::google::protobuf::int64 value) {
  
  v2_ = value;
  // @@protoc_insertion_point(field_set:pt.zj.xx.v2)
}

// uint32 v_x_3 = 3;
void xx::clear_v_x_3() {
  v_x_3_ = 0u;
}
::google::protobuf::uint32 xx::v_x_3() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.v_x_3)
  return v_x_3_;
}
void xx::set_v_x_3(::google::protobuf::uint32 value) {
  
  v_x_3_ = value;
  // @@protoc_insertion_point(field_set:pt.zj.xx.v_x_3)
}

// .pt.zj.obj_test test_1 = 5;
bool xx::has_test_1() const {
  return this != internal_default_instance() && test_1_ != NULL;
}
void xx::clear_test_1() {
  if (GetArenaNoVirtual() == NULL && test_1_ != NULL) delete test_1_;
  test_1_ = NULL;
}
const ::pt::zj::obj_test& xx::test_1() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.test_1)
  return test_1_ != NULL ? *test_1_
                         : *::pt::zj::obj_test::internal_default_instance();
}
::pt::zj::obj_test* xx::mutable_test_1() {
  
  if (test_1_ == NULL) {
    test_1_ = new ::pt::zj::obj_test;
  }
  // @@protoc_insertion_point(field_mutable:pt.zj.xx.test_1)
  return test_1_;
}
::pt::zj::obj_test* xx::release_test_1() {
  // @@protoc_insertion_point(field_release:pt.zj.xx.test_1)
  
  ::pt::zj::obj_test* temp = test_1_;
  test_1_ = NULL;
  return temp;
}
void xx::set_allocated_test_1(::pt::zj::obj_test* test_1) {
  delete test_1_;
  test_1_ = test_1;
  if (test_1) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:pt.zj.xx.test_1)
}

// repeated .pt.zj.obj_user user = 7;
int xx::user_size() const {
  return user_.size();
}
void xx::clear_user() {
  user_.Clear();
}
const ::pt::zj::obj_user& xx::user(int index) const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.user)
  return user_.Get(index);
}
::pt::zj::obj_user* xx::mutable_user(int index) {
  // @@protoc_insertion_point(field_mutable:pt.zj.xx.user)
  return user_.Mutable(index);
}
::pt::zj::obj_user* xx::add_user() {
  // @@protoc_insertion_point(field_add:pt.zj.xx.user)
  return user_.Add();
}
::google::protobuf::RepeatedPtrField< ::pt::zj::obj_user >*
xx::mutable_user() {
  // @@protoc_insertion_point(field_mutable_list:pt.zj.xx.user)
  return &user_;
}
const ::google::protobuf::RepeatedPtrField< ::pt::zj::obj_user >&
xx::user() const {
  // @@protoc_insertion_point(field_list:pt.zj.xx.user)
  return user_;
}

// string str = 8;
void xx::clear_str() {
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& xx::str() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.str)
  return str_.GetNoArena();
}
void xx::set_str(const ::std::string& value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pt.zj.xx.str)
}
#if LANG_CXX11
void xx::set_str(::std::string&& value) {
  
  str_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pt.zj.xx.str)
}
#endif
void xx::set_str(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.zj.xx.str)
}
void xx::set_str(const char* value, size_t size) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.zj.xx.str)
}
::std::string* xx::mutable_str() {
  
  // @@protoc_insertion_point(field_mutable:pt.zj.xx.str)
  return str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* xx::release_str() {
  // @@protoc_insertion_point(field_release:pt.zj.xx.str)
  
  return str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void xx::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    
  } else {
    
  }
  str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), str);
  // @@protoc_insertion_point(field_set_allocated:pt.zj.xx.str)
}

// .pt.zj.RET ret = 9;
void xx::clear_ret() {
  ret_ = 0;
}
::pt::zj::RET xx::ret() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.ret)
  return static_cast< ::pt::zj::RET >(ret_);
}
void xx::set_ret(::pt::zj::RET value) {
  
  ret_ = value;
  // @@protoc_insertion_point(field_set:pt.zj.xx.ret)
}

// string userName = 10;
void xx::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& xx::username() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.userName)
  return username_.GetNoArena();
}
void xx::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pt.zj.xx.userName)
}
#if LANG_CXX11
void xx::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pt.zj.xx.userName)
}
#endif
void xx::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.zj.xx.userName)
}
void xx::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.zj.xx.userName)
}
::std::string* xx::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:pt.zj.xx.userName)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* xx::release_username() {
  // @@protoc_insertion_point(field_release:pt.zj.xx.userName)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void xx::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:pt.zj.xx.userName)
}

// bool isBool = 11;
void xx::clear_isbool() {
  isbool_ = false;
}
bool xx::isbool() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.isBool)
  return isbool_;
}
void xx::set_isbool(bool value) {
  
  isbool_ = value;
  // @@protoc_insertion_point(field_set:pt.zj.xx.isBool)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace zj
}  // namespace pt

// @@protoc_insertion_point(global_scope)
