// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_gbmj.proto

#ifndef PROTOBUF_msg_5fgbmj_2eproto__INCLUDED
#define PROTOBUF_msg_5fgbmj_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace pt {
namespace zj {
class obj_test;
class obj_testDefaultTypeInternal;
extern obj_testDefaultTypeInternal _obj_test_default_instance_;
class obj_user;
class obj_userDefaultTypeInternal;
extern obj_userDefaultTypeInternal _obj_user_default_instance_;
class xx;
class xxDefaultTypeInternal;
extern xxDefaultTypeInternal _xx_default_instance_;
}  // namespace zj
}  // namespace pt

namespace pt {
namespace zj {

namespace protobuf_msg_5fgbmj_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_msg_5fgbmj_2eproto

enum obj_user_STATE {
  obj_user_STATE_S_SUCCESS = 0,
  obj_user_STATE_S_SUCCESS_1 = 1,
  obj_user_STATE_S_SUCCESS_2 = 2,
  obj_user_STATE_obj_user_STATE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  obj_user_STATE_obj_user_STATE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool obj_user_STATE_IsValid(int value);
const obj_user_STATE obj_user_STATE_STATE_MIN = obj_user_STATE_S_SUCCESS;
const obj_user_STATE obj_user_STATE_STATE_MAX = obj_user_STATE_S_SUCCESS_2;
const int obj_user_STATE_STATE_ARRAYSIZE = obj_user_STATE_STATE_MAX + 1;

const ::google::protobuf::EnumDescriptor* obj_user_STATE_descriptor();
inline const ::std::string& obj_user_STATE_Name(obj_user_STATE value) {
  return ::google::protobuf::internal::NameOfEnum(
    obj_user_STATE_descriptor(), value);
}
inline bool obj_user_STATE_Parse(
    const ::std::string& name, obj_user_STATE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<obj_user_STATE>(
    obj_user_STATE_descriptor(), name, value);
}
enum RET {
  RET_SUCCESS = 0,
  RET_ERROR = 1,
  RET_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  RET_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool RET_IsValid(int value);
const RET RET_MIN = RET_SUCCESS;
const RET RET_MAX = RET_ERROR;
const int RET_ARRAYSIZE = RET_MAX + 1;

const ::google::protobuf::EnumDescriptor* RET_descriptor();
inline const ::std::string& RET_Name(RET value) {
  return ::google::protobuf::internal::NameOfEnum(
    RET_descriptor(), value);
}
inline bool RET_Parse(
    const ::std::string& name, RET* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RET>(
    RET_descriptor(), name, value);
}
// ===================================================================

class obj_user : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pt.zj.obj_user) */ {
 public:
  obj_user();
  virtual ~obj_user();

  obj_user(const obj_user& from);

  inline obj_user& operator=(const obj_user& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const obj_user& default_instance();

  static inline const obj_user* internal_default_instance() {
    return reinterpret_cast<const obj_user*>(
               &_obj_user_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(obj_user* other);

  // implements Message ----------------------------------------------

  inline obj_user* New() const PROTOBUF_FINAL { return New(NULL); }

  obj_user* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const obj_user& from);
  void MergeFrom(const obj_user& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(obj_user* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef obj_user_STATE STATE;
  static const STATE S_SUCCESS =
    obj_user_STATE_S_SUCCESS;
  static const STATE S_SUCCESS_1 =
    obj_user_STATE_S_SUCCESS_1;
  static const STATE S_SUCCESS_2 =
    obj_user_STATE_S_SUCCESS_2;
  static inline bool STATE_IsValid(int value) {
    return obj_user_STATE_IsValid(value);
  }
  static const STATE STATE_MIN =
    obj_user_STATE_STATE_MIN;
  static const STATE STATE_MAX =
    obj_user_STATE_STATE_MAX;
  static const int STATE_ARRAYSIZE =
    obj_user_STATE_STATE_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  STATE_descriptor() {
    return obj_user_STATE_descriptor();
  }
  static inline const ::std::string& STATE_Name(STATE value) {
    return obj_user_STATE_Name(value);
  }
  static inline bool STATE_Parse(const ::std::string& name,
      STATE* value) {
    return obj_user_STATE_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated int32 arr = 2;
  int arr_size() const;
  void clear_arr();
  static const int kArrFieldNumber = 2;
  ::google::protobuf::int32 arr(int index) const;
  void set_arr(int index, ::google::protobuf::int32 value);
  void add_arr(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      arr() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_arr();

  // .pt.zj.obj_user.STATE s = 1;
  void clear_s();
  static const int kSFieldNumber = 1;
  ::pt::zj::obj_user_STATE s() const;
  void set_s(::pt::zj::obj_user_STATE value);

  // @@protoc_insertion_point(class_scope:pt.zj.obj_user)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > arr_;
  mutable int _arr_cached_byte_size_;
  int s_;
  mutable int _cached_size_;
  friend struct protobuf_msg_5fgbmj_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class obj_test : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pt.zj.obj_test) */ {
 public:
  obj_test();
  virtual ~obj_test();

  obj_test(const obj_test& from);

  inline obj_test& operator=(const obj_test& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const obj_test& default_instance();

  static inline const obj_test* internal_default_instance() {
    return reinterpret_cast<const obj_test*>(
               &_obj_test_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(obj_test* other);

  // implements Message ----------------------------------------------

  inline obj_test* New() const PROTOBUF_FINAL { return New(NULL); }

  obj_test* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const obj_test& from);
  void MergeFrom(const obj_test& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(obj_test* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string val_string = 1;
  void clear_val_string();
  static const int kValStringFieldNumber = 1;
  const ::std::string& val_string() const;
  void set_val_string(const ::std::string& value);
  #if LANG_CXX11
  void set_val_string(::std::string&& value);
  #endif
  void set_val_string(const char* value);
  void set_val_string(const char* value, size_t size);
  ::std::string* mutable_val_string();
  ::std::string* release_val_string();
  void set_allocated_val_string(::std::string* val_string);

  // @@protoc_insertion_point(class_scope:pt.zj.obj_test)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr val_string_;
  mutable int _cached_size_;
  friend struct protobuf_msg_5fgbmj_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class xx : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pt.zj.xx) */ {
 public:
  xx();
  virtual ~xx();

  xx(const xx& from);

  inline xx& operator=(const xx& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const xx& default_instance();

  static inline const xx* internal_default_instance() {
    return reinterpret_cast<const xx*>(
               &_xx_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(xx* other);

  // implements Message ----------------------------------------------

  inline xx* New() const PROTOBUF_FINAL { return New(NULL); }

  xx* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const xx& from);
  void MergeFrom(const xx& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(xx* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pt.zj.obj_user user = 7;
  int user_size() const;
  void clear_user();
  static const int kUserFieldNumber = 7;
  const ::pt::zj::obj_user& user(int index) const;
  ::pt::zj::obj_user* mutable_user(int index);
  ::pt::zj::obj_user* add_user();
  ::google::protobuf::RepeatedPtrField< ::pt::zj::obj_user >*
      mutable_user();
  const ::google::protobuf::RepeatedPtrField< ::pt::zj::obj_user >&
      user() const;

  // string str = 8;
  void clear_str();
  static const int kStrFieldNumber = 8;
  const ::std::string& str() const;
  void set_str(const ::std::string& value);
  #if LANG_CXX11
  void set_str(::std::string&& value);
  #endif
  void set_str(const char* value);
  void set_str(const char* value, size_t size);
  ::std::string* mutable_str();
  ::std::string* release_str();
  void set_allocated_str(::std::string* str);

  // string userName = 10;
  void clear_username();
  static const int kUserNameFieldNumber = 10;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // .pt.zj.obj_test test_1 = 5;
  bool has_test_1() const;
  void clear_test_1();
  static const int kTest1FieldNumber = 5;
  const ::pt::zj::obj_test& test_1() const;
  ::pt::zj::obj_test* mutable_test_1();
  ::pt::zj::obj_test* release_test_1();
  void set_allocated_test_1(::pt::zj::obj_test* test_1);

  // int64 v2 = 2;
  void clear_v2();
  static const int kV2FieldNumber = 2;
  ::google::protobuf::int64 v2() const;
  void set_v2(::google::protobuf::int64 value);

  // int32 v_1 = 1;
  void clear_v_1();
  static const int kV1FieldNumber = 1;
  ::google::protobuf::int32 v_1() const;
  void set_v_1(::google::protobuf::int32 value);

  // uint32 v_x_3 = 3;
  void clear_v_x_3();
  static const int kVX3FieldNumber = 3;
  ::google::protobuf::uint32 v_x_3() const;
  void set_v_x_3(::google::protobuf::uint32 value);

  // .pt.zj.RET ret = 9;
  void clear_ret();
  static const int kRetFieldNumber = 9;
  ::pt::zj::RET ret() const;
  void set_ret(::pt::zj::RET value);

  // bool isBool = 11;
  void clear_isbool();
  static const int kIsBoolFieldNumber = 11;
  bool isbool() const;
  void set_isbool(bool value);

  // @@protoc_insertion_point(class_scope:pt.zj.xx)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::pt::zj::obj_user > user_;
  ::google::protobuf::internal::ArenaStringPtr str_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::pt::zj::obj_test* test_1_;
  ::google::protobuf::int64 v2_;
  ::google::protobuf::int32 v_1_;
  ::google::protobuf::uint32 v_x_3_;
  int ret_;
  bool isbool_;
  mutable int _cached_size_;
  friend struct protobuf_msg_5fgbmj_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// obj_user

// .pt.zj.obj_user.STATE s = 1;
inline void obj_user::clear_s() {
  s_ = 0;
}
inline ::pt::zj::obj_user_STATE obj_user::s() const {
  // @@protoc_insertion_point(field_get:pt.zj.obj_user.s)
  return static_cast< ::pt::zj::obj_user_STATE >(s_);
}
inline void obj_user::set_s(::pt::zj::obj_user_STATE value) {
  
  s_ = value;
  // @@protoc_insertion_point(field_set:pt.zj.obj_user.s)
}

// repeated int32 arr = 2;
inline int obj_user::arr_size() const {
  return arr_.size();
}
inline void obj_user::clear_arr() {
  arr_.Clear();
}
inline ::google::protobuf::int32 obj_user::arr(int index) const {
  // @@protoc_insertion_point(field_get:pt.zj.obj_user.arr)
  return arr_.Get(index);
}
inline void obj_user::set_arr(int index, ::google::protobuf::int32 value) {
  arr_.Set(index, value);
  // @@protoc_insertion_point(field_set:pt.zj.obj_user.arr)
}
inline void obj_user::add_arr(::google::protobuf::int32 value) {
  arr_.Add(value);
  // @@protoc_insertion_point(field_add:pt.zj.obj_user.arr)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
obj_user::arr() const {
  // @@protoc_insertion_point(field_list:pt.zj.obj_user.arr)
  return arr_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
obj_user::mutable_arr() {
  // @@protoc_insertion_point(field_mutable_list:pt.zj.obj_user.arr)
  return &arr_;
}

// -------------------------------------------------------------------

// obj_test

// string val_string = 1;
inline void obj_test::clear_val_string() {
  val_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& obj_test::val_string() const {
  // @@protoc_insertion_point(field_get:pt.zj.obj_test.val_string)
  return val_string_.GetNoArena();
}
inline void obj_test::set_val_string(const ::std::string& value) {
  
  val_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pt.zj.obj_test.val_string)
}
#if LANG_CXX11
inline void obj_test::set_val_string(::std::string&& value) {
  
  val_string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pt.zj.obj_test.val_string)
}
#endif
inline void obj_test::set_val_string(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  val_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.zj.obj_test.val_string)
}
inline void obj_test::set_val_string(const char* value, size_t size) {
  
  val_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.zj.obj_test.val_string)
}
inline ::std::string* obj_test::mutable_val_string() {
  
  // @@protoc_insertion_point(field_mutable:pt.zj.obj_test.val_string)
  return val_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* obj_test::release_val_string() {
  // @@protoc_insertion_point(field_release:pt.zj.obj_test.val_string)
  
  return val_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void obj_test::set_allocated_val_string(::std::string* val_string) {
  if (val_string != NULL) {
    
  } else {
    
  }
  val_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val_string);
  // @@protoc_insertion_point(field_set_allocated:pt.zj.obj_test.val_string)
}

// -------------------------------------------------------------------

// xx

// int32 v_1 = 1;
inline void xx::clear_v_1() {
  v_1_ = 0;
}
inline ::google::protobuf::int32 xx::v_1() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.v_1)
  return v_1_;
}
inline void xx::set_v_1(::google::protobuf::int32 value) {
  
  v_1_ = value;
  // @@protoc_insertion_point(field_set:pt.zj.xx.v_1)
}

// int64 v2 = 2;
inline void xx::clear_v2() {
  v2_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 xx::v2() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.v2)
  return v2_;
}
inline void xx::set_v2(::google::protobuf::int64 value) {
  
  v2_ = value;
  // @@protoc_insertion_point(field_set:pt.zj.xx.v2)
}

// uint32 v_x_3 = 3;
inline void xx::clear_v_x_3() {
  v_x_3_ = 0u;
}
inline ::google::protobuf::uint32 xx::v_x_3() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.v_x_3)
  return v_x_3_;
}
inline void xx::set_v_x_3(::google::protobuf::uint32 value) {
  
  v_x_3_ = value;
  // @@protoc_insertion_point(field_set:pt.zj.xx.v_x_3)
}

// .pt.zj.obj_test test_1 = 5;
inline bool xx::has_test_1() const {
  return this != internal_default_instance() && test_1_ != NULL;
}
inline void xx::clear_test_1() {
  if (GetArenaNoVirtual() == NULL && test_1_ != NULL) delete test_1_;
  test_1_ = NULL;
}
inline const ::pt::zj::obj_test& xx::test_1() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.test_1)
  return test_1_ != NULL ? *test_1_
                         : *::pt::zj::obj_test::internal_default_instance();
}
inline ::pt::zj::obj_test* xx::mutable_test_1() {
  
  if (test_1_ == NULL) {
    test_1_ = new ::pt::zj::obj_test;
  }
  // @@protoc_insertion_point(field_mutable:pt.zj.xx.test_1)
  return test_1_;
}
inline ::pt::zj::obj_test* xx::release_test_1() {
  // @@protoc_insertion_point(field_release:pt.zj.xx.test_1)
  
  ::pt::zj::obj_test* temp = test_1_;
  test_1_ = NULL;
  return temp;
}
inline void xx::set_allocated_test_1(::pt::zj::obj_test* test_1) {
  delete test_1_;
  test_1_ = test_1;
  if (test_1) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:pt.zj.xx.test_1)
}

// repeated .pt.zj.obj_user user = 7;
inline int xx::user_size() const {
  return user_.size();
}
inline void xx::clear_user() {
  user_.Clear();
}
inline const ::pt::zj::obj_user& xx::user(int index) const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.user)
  return user_.Get(index);
}
inline ::pt::zj::obj_user* xx::mutable_user(int index) {
  // @@protoc_insertion_point(field_mutable:pt.zj.xx.user)
  return user_.Mutable(index);
}
inline ::pt::zj::obj_user* xx::add_user() {
  // @@protoc_insertion_point(field_add:pt.zj.xx.user)
  return user_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pt::zj::obj_user >*
xx::mutable_user() {
  // @@protoc_insertion_point(field_mutable_list:pt.zj.xx.user)
  return &user_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pt::zj::obj_user >&
xx::user() const {
  // @@protoc_insertion_point(field_list:pt.zj.xx.user)
  return user_;
}

// string str = 8;
inline void xx::clear_str() {
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& xx::str() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.str)
  return str_.GetNoArena();
}
inline void xx::set_str(const ::std::string& value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pt.zj.xx.str)
}
#if LANG_CXX11
inline void xx::set_str(::std::string&& value) {
  
  str_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pt.zj.xx.str)
}
#endif
inline void xx::set_str(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.zj.xx.str)
}
inline void xx::set_str(const char* value, size_t size) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.zj.xx.str)
}
inline ::std::string* xx::mutable_str() {
  
  // @@protoc_insertion_point(field_mutable:pt.zj.xx.str)
  return str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* xx::release_str() {
  // @@protoc_insertion_point(field_release:pt.zj.xx.str)
  
  return str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void xx::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    
  } else {
    
  }
  str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), str);
  // @@protoc_insertion_point(field_set_allocated:pt.zj.xx.str)
}

// .pt.zj.RET ret = 9;
inline void xx::clear_ret() {
  ret_ = 0;
}
inline ::pt::zj::RET xx::ret() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.ret)
  return static_cast< ::pt::zj::RET >(ret_);
}
inline void xx::set_ret(::pt::zj::RET value) {
  
  ret_ = value;
  // @@protoc_insertion_point(field_set:pt.zj.xx.ret)
}

// string userName = 10;
inline void xx::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& xx::username() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.userName)
  return username_.GetNoArena();
}
inline void xx::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pt.zj.xx.userName)
}
#if LANG_CXX11
inline void xx::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pt.zj.xx.userName)
}
#endif
inline void xx::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.zj.xx.userName)
}
inline void xx::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.zj.xx.userName)
}
inline ::std::string* xx::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:pt.zj.xx.userName)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* xx::release_username() {
  // @@protoc_insertion_point(field_release:pt.zj.xx.userName)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void xx::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:pt.zj.xx.userName)
}

// bool isBool = 11;
inline void xx::clear_isbool() {
  isbool_ = false;
}
inline bool xx::isbool() const {
  // @@protoc_insertion_point(field_get:pt.zj.xx.isBool)
  return isbool_;
}
inline void xx::set_isbool(bool value) {
  
  isbool_ = value;
  // @@protoc_insertion_point(field_set:pt.zj.xx.isBool)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace zj
}  // namespace pt

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::pt::zj::obj_user_STATE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pt::zj::obj_user_STATE>() {
  return ::pt::zj::obj_user_STATE_descriptor();
}
template <> struct is_proto_enum< ::pt::zj::RET> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pt::zj::RET>() {
  return ::pt::zj::RET_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_5fgbmj_2eproto__INCLUDED
