set(PROJECT_VERSION_MAJOR 11)
set(PROJECT_VERSION_MINOR 12)
set(PROJECT_VERSION_PATCH 13)
set(PROJECT_VERSION_TWEAK 14)
set(PROJECT_VERSION 
    "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}.${PROJECT_VERSION_TWEAK}"
    )
