

INCLUDE(${CMAKE_HOME_DIRECTORY}/cmake/FindVcpkg.cmake)

MESSAGE(STATUS "start find boost_vcpkg vcpkg_root_dir ${VCPKG_ROOT_DIR}")
MESSAGE(STATUS "start find boost_vcpkg vcpkg_root_include_dir ${VCPKG_ROOT_INCLUDE_DIR}")


##[[
MESSAGE(STATUS "xxxxx debug release CMAKE_BUILD_TYPE ${CMAKE_BUILD_TYPE}")
MESSAGE(STATUS "xxxxx debug release CMAKE_C_FLAGS_DEBUG ${CMAKE_C_FLAGS_DEBUG}")
MESSAGE(STATUS "xxxxx debug release CMAKE_C_FLAGS_RELEASE ${CMAKE_C_FLAGS_RELEASE}")
MESSAGE(STATUS "xxxxx debug release CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG}")
MESSAGE(STATUS "xxxxx debug release CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE}")
#]]

## boost include
SET(BOOST_INCLUDE_DIR ${VCPKG_ROOT_INCLUDE_DIR}
    CACHE STRING "boost include"
)

IF(NOT BOOST_INCLUDE_DIR)
    MESSAGE(FATAL_ERROR "Can't find BOOST_INCLUDE_DIR: ${BOOST_INCLUDE_DIR}")
ELSE()
    MESSAGE(STATUS "Set BOOST_INCLUDE_DIR: ${BOOST_INCLUDE_DIR}")
ENDIF()


## 设置boost library 目录 boost .lib/.so
IF(WIN32)
    SET(BOOST_LIBRARY_DIR ${VCPKG_ROOT_DIR}\\debug\\lib)
ELSEIF(UNIX)
    SET(BOOST_LIBRARY_DIR "/usr/local/lib")
ENDIF(WIN32)

IF(NOT BOOST_LIBRARY_DIR)
    MESSAGE(FATAL_ERROR "Can't find BOOST_LIBRARY_DIR: ${BOOST_LIBRARY_DIR}")
  ELSE()
    MESSAGE(STATUS "Set BOOST_LIBRARY_DIR: ${BOOST_LIBRARY_DIR}")
ENDIF()

## boost .lib 命名规则
IF(WIN32)
    SET(BOOST_LIB_PREFIX "")
    SET(BOOST_LIB_POSTFIX "-vc140-mt-gd.lib")
ELSE(UNIX)
    SET(BOOST_LIB_PREFIX "lib")
    SET(BOOST_LIB_POSTFIX ".so")
ENDIF()
MESSAGE("boost libraries name rule: ${BOOST_LIB_PREFIX}boost_xxx${BOOST_LIB_POSTFIX}")


## 添加需要的boost libraries
SET(BOOST_LIBRARIES_LIST boost_log boost_thread boost_date_time boost_filesystem boost_system)

SET(BOOST_LIBRARIES ""   CACHE STRING "boost libraries")
FOREACH(LIB_NAME ${BOOST_LIBRARIES_LIST})
    SET(BOOST_LIB_NAME "${BOOST_LIB_PREFIX}${LIB_NAME}${BOOST_LIB_POSTFIX}")
    FIND_LIBRARY(${LIB_NAME}_PATH ${BOOST_LIB_NAME} PATHS ${BOOST_LIBRARY_DIR})
    IF(NOT ${LIB_NAME}_PATH)
        MESSAGE(FATAL_ERROR "Can't find  ${BOOST_LIB_NAME} ${BOOST_LIBRARY_DIR}")
    ELSE()
        MESSAGE(STATUS "find boost lib: ${${LIB_NAME}_PATH} ${BOOST_LIB_NAME}")
    ENDIF()

    SET(BOOST_LIBRARIES "${BOOST_LIBRARIES}\n${${LIB_NAME}_PATH}")
    
ENDFOREACH()

STRING(STRIP ${BOOST_LIBRARIES} BOOST_LIBRARIES)
#SET(BOOST_LIBRARIES ${BOOST_LIBRARIES_LIST} CACHE STRING "boost libraries")