
SET(VCPKG_ROOT_DIR ${VCPKG_DIR})
#[[
IF(WIN32)
    SET(VCPKG_ROOT_DIR ${VCPKG_DIR}\\installed)
ELSEIF(UNIX)
    SET(VCPKG_ROOT_DIR ${VCPKG_DIR}/installed)
ENDIF(WIN32)
]]

IF(WIN32)
    IF(PLATFORM_TARGET STREQUAL "x86")
        SET(VCPKG_ROOT_DIR ${VCPKG_DIR}\\x86-windows)
    ELSE()
        SET(VCPKG_ROOT_DIR ${VCPKG_DIR}\\x64-windows)
    ENDIF()
    SET(VCPKG_ROOT_INCLUDE_DIR ${VCPKG_ROOT_DIR}\\include)
ELSEIF(UNIX)
    IF(PLATFORM_TARGET STREQUAL "x86")
        SET(VCPKG_ROOT_DIR ${VCPKG_DIR}/x86-windows)
    ELSE()
        SET(VCPKG_ROOT_DIR ${VCPKG_DIR}/x64-windows)
    ENDIF()
    SET(VCPKG_ROOT_INCLUDE_DIR ${VCPKG_ROOT_DIR}/include)
ENDIF(WIN32)

